### ISSUE TITLE
support semantic versioning

### ISSUE THREAD

**Issue by walidsa3d** [javrasya/version-updater#1]
would you mind to support semantic versioning? I would like just to bump the version without the need to know the whole version string

**Comment by javrasya** [comment]
To be clear, are you asking a functionality like;

```
update_version --major
update_version --minor
update_version --patch
```

**Comment by walidsa3d** [comment]
That's exactly what I want.

**Comment by javrasya** [comment]
Please see updated documentation.

**Comment by walidsa3d** [comment]
That works, thanks
